jobs:
  include:
  - language: ruby
    addons:
      apt:
        packages:
          - doxygen
    script:
      - doxygen Doxyfile
    deploy:
      provider: pages
      skip_cleanup: true
      local_dir: Engine/Docs/html
      token: $GH_REPO_TOKEN
      on:
        branch: main