set(CMAKE_SYSTEM_VERSION 10.0.19041.0)
set(WINDOWS TRUE)
set(PLATFORM_NAME "Windows")

add_definitions(-DAE_WINDOWS -D_WINDOWS -DWIN32 -D_WIN32 -D_WIN64)

set(CMAKE_CONFIGURATION_TYPES Debug Profile Release)
set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES}" CACHE STRING "Reset the configurations to what we need" FORCE)